driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-5.10-i386
  - name: centos-6.5
  - name: centos-6.5-i386
  - name: fedora-19
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_repo]
