---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
  run_list:
    - recipe[apt]
- name: centos-6.5
  driver:
    box: opscode-centos-6.5
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.5_chef-11.4.4.box
  run_list:
    - recipe[yum]

suites:
- name: default
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes: 
    go: 
      owner: 'vagrant'
      group: 'vagrant'
