---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: centos-6.4
- name: centos-5.9

provisioner:
    name: chef_zero

suites:
- name: default
  run_list:
    - "recipe[modules]"
